server:
 port: 8090

spring:
 datasource:
#  url: jdbc:mysql://localhost:3305/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT+8
  url: jdbc:mysql://localhost:3306/wms
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

 mybatis-plus:
  type-aliases-package: com.wms.entity

 mybatis:
  mapper-locations: classpath:mapper/RecordMapper.xml
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB

#aliyun oss
alioss:
 endpoint: oss-cn-chengdu.aliyuncs.com
 accessKeyId:
 accessKeySecret:
 bucketName:

mybatis-plus:
 configuration:
  map-underscore-to-camel-case: false
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
